# cbcs/osha locations ----

cbcs.locations <- data.frame(
  
  Location = c(
    "BREVARD (COCOA) - DIST",
    "BREVARD (COCOA) - SALES",
    "BREVARD (COCOA) - ES",
    "BREVARD (COCOA) - FLEET",
    "BROWARD - DIST",
    "BROWARD - PROD",
    "BROWARD - SALES",
    "DAYTONA - DIST",
    "DAYTONA - ES",
    "DAYTONA - SALES",
    "DUNEDIN - SALES",
    "FT. MYERS - DIST",
    "FT. MYERS - ES",
    "FT. MYERS - FLEET",
    "FT. MYERS - SALES",
    "FT. PIERCE - DIST",
    "FT. PIERCE - SALES",
    "GAINESVILLE - SALES",
    "JACKSONVILLE - DIST",
    "JACKSONVILLE - FLEET",
    "JACKSONVILLE - PROD",
    "JACKSONVILLE - SALES",
    "JACKSONVILLE H2 - DIST",
    "LAKELAND - DIST",
    "LAKELAND - SALES",
    "MIAMI DADE - DIST",
    "MIAMI DADE - SALES",
    "OCALA - SALES",
    "ORLANDO - DIST",
    "ORLANDO - FLEET",
    "ORLANDO - PROD",
    "ORLANDO - SALES",
    "ORLANDO MRC - DIST",
    "ORLANDO MRC - ES",
    "PALM BEACH - DIST",
    "PALM BEACH - SALES",
    "SARASOTA - DIST",
    "SARASOTA - SALES",
    "SPRING HILL - DIST",
    "SPRING HILL - SALES",
    "TAMPA DC - DIST",
    "TAMPA DC - SALES",
    "TAMPA PC - ES",
    "TAMPA PC - PROD",
    "THE KEYS - ES",
    "HEADQUARTERS - SALES",
    "HEADQUARTERS - ADMIN",
    "THE KEYS - DIST",
    "THE KEYS - FLEET",
    "THE KEYS - SALES",
    "DAYTONA - ADMIN",
    "DAYTONA - FLEET",
    "FT. MYERS - ADMIN",
    "FT. PIERCE- ES",
    "FT. PIERCE- FLEET",
    "FT. PIERCE- ADMIN",
    "GAINESVILLE- DIST",
    "GAINESVILLE- ES",
    "GAINESVILLE- FLEET",
    "GAINESVILLE- ADMIN",
    "BROWARD- ES",
    "BROWARD- FLEET",
    "BROWARD- ADMIN",
    "JACKSONVILLE- ES",
    "JACKSONVILLE- ADMIN",
    "LAKELAND- ES",
    "LAKELAND- FLEET",
    "LAKELAND- ADMIN",
    "ORLANDO- ES",
    "ORLANDO- ADMIN",
    "ORLANDO MRC- SALES",
    "SARASOTA- ES",
    "SARASOTA- ADMIN",
    "SARASOTA- FLEET",
    "MIAMI DADE- ES",
    "MIAMI DADE- FLEET",
    "MIAMI DADE- ADMIN",
    "TAMPA DC- ES",
    "TAMPA DC- FLEET",
    "TAMPA DC- ADMIN",
    "TAMPA PC- FLEET",
    "PALM BEACH- ES",
    "PALM BEACH- FLEET",
    "PALM BEACH- ADMIN"
    
  ),

  Section = c(
    "Distribution",
    "Sales",
    "Equipment Services",
    "Fleet",
    "Distribution",
    "Production",
    "Sales",
    "Distribution",
    "Equipment Services",
    "Sales",
    "Sales",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Sales",
    "Distribution",
    "Sales",
    "Sales",
    "Distribution",
    "Fleet",
    "Production",
    "Sales",
    "Distribution",
    "Distribution",
    "Sales",
    "Distribution",
    "Sales",
    "Sales",
    "Distribution",
    "Fleet",
    "Production",
    "Sales",
    "Distribution",
    "Equipment Services",
    "Distribution",
    "Sales",
    "Distribution",
    "Sales",
    "Distribution",
    "Sales",
    "Distribution",
    "Sales",
    "Equipment Services",
    "Production",
    "Equipment Services",
    "Sales",
    "Administration",
    "Distribution",
    "Fleet",
    "Sales",
    "Administration",
    "Fleet",
    "Administration",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Equipment Services",
    "Administration",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Equipment Services",
    "Administration",
    "Sales",
    "Equipment Services",
    "Administration",
    "Fleet",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Fleet",
    "Equipment Services",
    "Fleet",
    "Administration"
  ),

  Facility = c(
    "Brevard",
    "Brevard",
    "Brevard",
    "Brevard",
    "Broward",
    "Broward",
    "Broward",
    "Daytona",
    "Daytona",
    "Daytona",
    "Dunedin",
    "Fort Myers",
    "Fort Myers",
    "Fort Myers",
    "Fort Myers",
    "Fort Pierce",
    "Fort Pierce",
    "Gainesville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Lakeland",
    "Lakeland",
    "South Dade",
    "South Dade",
    "Gainesville",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando Mrc",
    "Palm Beach",
    "Palm Beach",
    "Sarasota",
    "Sarasota",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa PC",
    "Tampa PC",
    "The Keys",
    "Headquarters",
    "Headquarters",
    "The Keys",
    "The Keys",
    "The Keys",
    "Daytona",
    "Daytona",
    "Fort Myers",
    "Fort Pierce",
    "Fort Pierce",
    "Fort Pierce",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Broward",
    "Broward",
    "Broward",
    "Jacksonville",
    "Jacksonville",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Orlando",
    "Orlando",
    "Orlando Mrc",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "South Dade",
    "South Dade",
    "South Dade",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa PC",
    "Palm Beach",
    "Palm Beach",
    "Palm Beach"
  )
)

cbcs.locations <- cbcs.locations %>% 
  mutate(Location = as.character(Location))

# exempt locations ----

exempt.locations <- data.frame(
  
  Facility = c(
    "Brevard",
    "Brevard",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Daytona",
    "Daytona",
    "Dunedin",
    "Dunedin",
    "Dunedin",
    "Fort Myers",
    "Fort Myers",
    "Fort Myers",
    "Fort Pierce",
    "Fort Pierce",
    "Fort Pierce",
    "Gainesville",
    "Gainesville",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Lakeland",
    "Lakeland",
    "Miami Dade",
    "Miami Dade",
    "Miami Dade",
    "Miami Dade",
    "Miami Dade",
    "Miami Dade",
    "Ocala",
    "Orlando Mrc",
    "Orlando Mrc",
    "Orlando Mrc",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Palm Beach",
    "Palm Beach",
    "Palm Beach",
    "Sarasota",
    "Sarasota",
    "Orlando",
    "Tampa DC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "The Keys",
    "Headquarters",
    "Orlando Mrc",
    "Orlando",
    "Headquarters",
    "Jacksonville",
    "Miami Dade",
    "Broward",
    "Palm Beach",
    "Orlando",
    "Broward",
    "Jacksonville"
    # "Palm Beach"
  ),
  
  Section = c(
    "Distribution",
    "Equipment Services",
    "Sales",
    "Distribution",
    "Production",
    "Administration",
    "Distribution",
    "Equipment Services",
    "Administration",
    "Sales",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Distribution",
    "Distribution",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Administration",
    "Distribution",
    "Equipment Services",
    "Distribution",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Distribution",
    "Administration",
    "Distribution",
    "Administration",
    "Administration",
    "Distribution",
    "Sales",
    "Sales",
    "Administration",
    "Administration",
    "Administration",
    "Distribution",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Equipment Services",
    "Distribution",
    "Production",
    "Administration",
    "Administration",
    "Sales",
    "Distribution",
    "Sales",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Distribution",
    "Distribution",
    "Administration",
    "Sales",
    "Distribution",
    "Equipment Services",
    "Administration",
    "Administration",
    "Distribution",
    "Sales",
    "Equipment Services",
    "Distribution",
    "Distribution",
    "Administration",
    "Equipment Service",
    "Production",
    "Sales",
    "Distribution",
    "Administration",
    "Sales",
    "Administration",
    "Administration",
    "Administration",
    "Administration",
    "Distribution",
    "Equipment Services",
    "Sales",
    "Distribution",
    "Equipment Services",
    "Distribution",
    "Distribution",
    "Production",
    "Distribution",
    "Equipment Services",
    "Production",
    "Administration",
    "Administration",
    "Administration",
    "Distribution",
    "Sales",
    "Administration",
    "Distribution",
    "Sales",
    "Sales",
    "Sales",
    "Sales",
    "Sales",
    "Sales",
    "Sales",
    "Sales",
    "Sales",
    "Sales",
    "Sales"
    # "Administration"
    
  ),
  
  `Personnel Area Desc` = c(
    "Brevard, FL",
    "Brevard, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Broward, FL",
    "Daytona, FL",
    "Daytona, FL",
    "Dunedin, FL",
    "Dunedin, FL",
    "Dunedin, FL",
    "Fort Myers, FL",
    "Fort Myers, FL",
    "Fort Myers, FL",
    "Fort Pierce, FL",
    "Fort Pierce, FL",
    "Fort Pierce, FL",
    "Gainesville, FL",
    "Gainesville, FL",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Headquarter Office",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Jacksonville, FL",
    "Lakeland, FL",
    "Lakeland, FL",
    "Miami-Dade, FL",
    "Miami-Dade, FL",
    "Miami-Dade, FL",
    "Miami-Dade, FL",
    "Miami-Dade, FL",
    "Miami-Dade, FL",
    "Ocala, FL",
    "Orlando Field Servic",
    "Orlando Field Servic",
    "Orlando Field Servic",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Orlando, FL",
    "Palm Beach, FL",
    "Palm Beach, FL",
    "Palm Beach, FL",
    "Sarasota, FL",
    "Sarasota, FL",
    "Sebring, FL",
    "Spring Hill, FL",
    "Tampa MFG, FL",
    "Tampa MFG, FL",
    "Tampa MFG, FL",
    "Tampa MFG, FL",
    "Tampa MFG, FL",
    "Tampa MFG, FL",
    "Tampa MFG, FL",
    "Tampa, FL",
    "Tampa, FL",
    "Tampa, FL",
    "The Keys, FL",
    "Headquarter Office",
    "Orlando Field Servic",
    "Orlando, FL",
    "Headquarter Office",
    "Jacksonville, FL",
    "Miami-Dade, FL",
    "Broward, FL",
    "Palm Beach, FL",
    "Orlando, FL",
    "Broward, FL",
    "Jacksonville, FL"
    # "Palm Beach, FL"
    
  ),
  
  `L4 Org Unit Name` = c(
    "Franchise Field Operations",
    "MRC & Field Service",
    "Marketing",
    "Franchise Field Operations",
    "Broward Production Center",
    "Environmental Health Safety & Sustain",
    "Distribution Operations",
    "MRC & Field Service",
    "Corp Development & Gov Relations",
    "Customer Management",
    "Field IT",
    "Security",
    "Talent and Learning",
    "Corporate HR & Ops",
    "Controller",
    "Controller",
    "Franchise Field Operations",
    "Franchise Field Operations",
    "MRC & Field Service",
    "Tax System & Technology",
    "Franchise Field Operations",
    "MRC & Field Service",
    "Controller",
    "Franchise Field Operations",
    "Controller",
    "MRC & Field Service",
    "Franchise Field Operations",
    "Business Services and Systems",
    "Franchise Field Operations",
    "PGM and Planning",
    "Security",
    "Distribution Operations",
    "Marketing",
    "Customer Management",
    "Talent and Learning",
    "Corporate Development",
    "Field IT",
    "Controller",
    "Corporate HR & Ops",
    "SAP Master Data",
    "GTM & Insights",
    "Corp Development & Gov Relations",
    "Business Services and Systems",
    "Total Rewards",
    "Environmental Health Safety & Sustain",
    "Talent Acquisition",
    "Communications",
    "Business Services and Systems",
    "Corporate Development",
    "MRC & Field Service",
    "Franchise Field Operations",
    "Jacksonville Manufacturing",
    "Corporate HR & Ops",
    "Security",
    "Marketing",
    "Distribution Operations",
    "Customer Management",
    "Engineering",
    "Field IT",
    "Environmental Health Safety & Sustain",
    "Talent and Learning",
    "Franchise Field Operations",
    "Distribution Operations",
    "Franchise Field Operations",
    "Customer Management",
    "Distribution Operations",
    "MRC & Field Service",
    "Corporate Development",
    "Security",
    "Franchise Field Operations",
    "Customer Management",
    "MRC & Field Service",
    "Franchise Field Operations",
    "Franchise Field Operations",
    "Business Services and Systems",
    "MRC & Field Service",
    "Orlando Manufacturing",
    "Customer Management",
    "Distribution Operations",
    "Field IT",
    "Marketing",
    "Corporate HR & Ops",
    "Environmental Health Safety & Sustain",
    "Talent and Learning",
    "Security",
    "Franchise Field Operations",
    "MRC & Field Service",
    "Customer Management",
    "Franchise Field Operations",
    "MRC & Field Service",
    "Franchise Field Operations",
    "Franchise Field Operations",
    "Tampa Production Center",
    "Distribution Operations",
    "MRC & Field Service",
    "Quality",
    "Engineering",
    "Environmental Health Safety & Sustain",
    "Security",
    "Franchise Field Operations",
    "Marketing",
    "Corporate HR & Ops",
    "Franchise Field Operations",
    "Customer Management – Retail",
    "Customer Management – FSOP",
    "Customer Management – FSOP",
    "Customer Management – FSOP",
    "Customer Management – Retail",
    "Customer Management – FSOP",
    "Customer Management – FSOP",
    "Customer Management – Retail",
    "Customer Management – Retail",
    "Customer Management – Retail",
    "Customer Management – FSOP"
    # "Business Services and Systems"
    
  )
  
)

exempt.locations <- exempt.locations %>% 
  mutate(L4.Org.Unit.Name = as.character(L4.Org.Unit.Name))

Encoding(exempt.locations$L4.Org.Unit.Name) <- "UTF-8"

# nonexempt locations ----

non.exempt.locations <- data.frame(
  
  Facility = c(
    "The Keys",
    "The Keys",
    "The Keys",
    "The Keys",
    "Brevard",
    "Brevard",
    "Brevard",
    "Brevard",
    "Brevard",
    "Brevard",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Daytona",
    "Dunedin",
    "Fort Myers",
    "Fort Myers",
    "Fort Myers",
    "Fort Myers",
    "Fort Myers",
    "Fort Myers",
    "Fort Myers",
    "Fort Pierce",
    "Fort Pierce",
    "Fort Pierce",
    "Fort Pierce",
    "Fort Pierce",
    "Fort Pierce",
    "Fort Pierce",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Gainesville",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Headquarters",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Broward",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Jacksonville",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Lakeland",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Orlando",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "Sarasota",
    "South Dade",
    "South Dade",
    "South Dade",
    "South Dade",
    "South Dade",
    "South Dade",
    "South Dade",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa DC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Tampa PC",
    "Palm Beach",
    "Palm Beach",
    "Palm Beach",
    "Palm Beach",
    "Palm Beach",
    "Palm Beach",
    "Palm Beach"

  ),
  
  Section = c(
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Sales",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Sales",
    "Administration",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Administration",
    "Fleet",
    "Sales",
    "Sales",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Administration",
    "Fleet",
    "Sales",
    "Sales",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Sales",
    "Sales",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Sales",
    "Sales",
    "Sales",
    "Sales",
    "Sales",
    "Administration",
    "Administration",
    "Production",
    "Administration",
    "Production",
    "Production",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Sales",
    "Sales",
    "Distribution",
    "Distribution",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Administration",
    "Production",
    "Production",
    "Production",
    "Production",
    "Sales",
    "Sales",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Sales",
    "Sales",
    "Fleet",
    "Distribution",
    "Distribution",
    "Distribution",
    "Administration",
    "Administration",
    "Production",
    "Production",
    "Production",
    "Production",
    "Sales",
    "Sales",
    "Equipment Services",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Administration",
    "Fleet",
    "Sales",
    "Sales",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Sales",
    "Sales",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Sales",
    "Sales",
    "Equipment Services",
    "Fleet",
    "Production",
    "Production",
    "Production",
    "Production",
    "Production",
    "Production",
    "Production",
    "Administration",
    "Distribution",
    "Distribution",
    "Distribution",
    "Distribution",
    "Equipment Services",
    "Fleet",
    "Administration",
    "Sales",
    "Sales"
    
  ),
  
  `Cost Center Desc.` = c(
    "BIG PINE KEY SC DELV",
    "BIG PINE KEY SC EQSV",
    "",
    "BIG PINE KEY SC MERC",
    "Brevard SC Delv",
    "Brevard SC Whse",
    "Brevard SC EQSV",
    "Brevard SC Fleet",
    "Brevard SC Merch",
    "Brevard SC G&A",
    "Daytona SC Delv",
    "Daytona SC Whse",
    "Daytona SC EQSV",
    "Daytona SC G&A",
    "Daytona SC Fleet",
    "Daytona SC Merch",
    "",
    "CF-Ft. Myers WHSE",
    "CF-Ft. Myers Deliver",
    "CF-Ft. Myers EQSV",
    "CF-Ft. Myers G&A",
    "CF-Ft. Myers Fleet",
    "CF-Ft. Myers Merch",
    "CF-Ft. Myers S&M",
    "CF-Ft. Pierce WHSE",
    "CF-Ft. Pierce Delive",
    "CF-Ft. Pierce EQSV",
    "",
    "CF-Ft. Pierce G&A",
    "CF-Ft. Pierce Merch",
    "CF-Ft. Pierce S&M",
    "Gainesville SC Whse",
    "Gainesville SC Delv",
    "Gainesville SC EQSV",
    "Gainesville SC Fleet",
    "Gainesville SC G&A",
    "Gainesville SC Merch",
    "Gainesville SC S&M",
    "CCBF HQ DSD Plan",
    "CCBF HQ Mktg",
    "CF-Fleet HQ",
    "CCBF HQ PRGM",
    "CCBF HQ Admin",
    "HOLLYWOOD PC DIR PRO",
    "HOLLYWOOD PC G&A",
    "HOLLYWOOD PC MAINT",
    "HOLLYWOOD PC QC",
    "HOLLYWOOD PC WHSE",
    "HOLLYWOOD SC DELV",
    "HOLLYWOOD SC EQSV",
    "HOLLYWOOD SC FLEET",
    "HOLLYWOOD SC G&A",
    "HOLLYWOOD SC MERCH",
    "HOLLYWOOD SC S&M",
    "HOLLYWOOD SC WHSE",
    "Jacksonville PC WHSE",
    "Jacksonville SC Delv",
    "Jacksonville SC Whse",
    "Jacksonville SC EQSV",
    "Jacksonville SC Flee",
    "Jacksonville PC G&A",
    "Jacksonville SC G&A",
    "Jacksonville PC FRT",
    "JacksonvillePC Maint",
    "JacksonvillePCDirPro",
    "Jacksonville PC QC",
    "Jacksonville SC Merc",
    "Jacksonville SC S&M",
    "CF-Lakeland WHSE",
    "CF-Lakeland Delivery",
    "CF-Lakeland EQSV",
    "CF-Lakeland Fleet",
    "CF-Lakeland G&A",
    "CF-Lakeland Merch",
    "CF-Lakeland S&M",
    "Orlando SC Fleet",
    "Orlando SC Delv",
    "Orlando SC Whse",
    "Orlando PC WHSE",
    "Orlando SC G&A",
    "Orlando PC G&A",
    "Orlando PC Dir Prod",
    "Orlando PC FRT",
    "Orlando PC Maint",
    "Orlando PC QC",
    "Orlando SC Merch",
    "Orlando SC S&M",
    "Orlando SC EQSV",
    "CF-Sarasota WHSE",
    "CF-Sarasota Delivery",
    "CF-Sarasota EQSV",
    "CF-Sarasota G&A",
    "CF-Sarasota Fleet",
    "CF-Sarasota Merch",
    "CF-Sarasota S&M",
    "SOUTH DADE SC WHSE",
    "SOUTH DADE SC DELV",
    "SOUTH DADE SC EQSV",
    "SOUTH DADE SC FLEET",
    "SOUTH DADE SC G&A",
    "SOUTH DADE SC MERCH",
    "SOUTH DADE SC S&M",
    "CF-Tampa Madison Del",
    "CF-Tampa Madison Whs",
    "",
    "CF-Tampa Madison Fle",
    "CF-Tampa Madison G&A",
    "CF-Tampa Madison Mer",
    "CF-Tampa Madison S&M",
    "CF-Tampa Sabal EQSV",
    "",
    "TAMPA SMWTR DIR PROD",
    "TAMPA SMWTR MAINT",
    "TAMPA SMWTR QC",
    "Tampa PC Dir Prod",
    "Tampa PC Freight",
    "Tampa PC Maint",
    "Tampa PC QC",
    "Tampa PC G&A",
    "Tampa PC WHSE",
    "TAMPA SMWTR WHSE",
    "WEST PALM SC DELV",
    "WEST PALM SC WHSE",
    "WEST PALM SC EQSV",
    "WEST PALM SC FLEET",
    "WEST PALM SC G&A",
    "WEST PALM SC MERCH",
    "WEST PALM SC S&M"
    
  )
  
)

exempt.locations <- exempt.locations %>% 
  rename(`L4 Org Unit Name` = L4.Org.Unit.Name,
         `Personnel Area Desc` = Personnel.Area.Desc)

# expenditures locations ----

expenditures.locations <- data.frame(
  
  Location = c(
    
  ),
  
  Section = c(
    
  ),
  
  `Cost Center` = c(
    
  )
  
)